image: registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest

variables:
    TRY_CACHE: "no"

include:
    - '/packages/wut-linux/ci.yml'
    - '/packages/wut-osx/ci.yml'
    - '/packages/pkgconf/ci.yml'
    - '/packages/libiosuhax/ci.yml'
    - '/packages/libdynamiclibs/ci.yml'
    - '/packages/libutils/ci.yml'
    - '/packages/curl-headers/ci.yml'
    - '/packages/sdl2/ci.yml'
    # devkitPPC transitional packages
    - '/packages/libmad/ci.yml'
    - '/packages/glm/ci.yml'

stages:
    - container # Docker bits
    - toolchain # Essential toolchain bits - wut etc.
    - libraries # Libraries or groups of libraries that stand alone
    - libraries2 # Libraries that depend on things from "libraries"
    - deploy

before_script:
    - pacman -Sy

pages:
    stage: deploy
    before_script:
        - pacman -Sy
        - cd $CI_PROJECT_DIR
        - gpg --batch --import fling-key.pub
        - echo "$FLING_SIGN_KEY" | gpg --batch --import
    script:
#        - wget https://gitlab.com/QuarkTheAwesome/wiiu-fling/-/jobs/artifacts/master/download?job=pages -O out.zip
#        - unzip out.zip &&
        - mkdir -p $CI_PROJECT_DIR/public/ && cp $CI_PROJECT_DIR/packages/*/*.pkg* $CI_PROJECT_DIR/public/
        - cp fling-key.pub $CI_PROJECT_DIR/public/
        - cd $CI_PROJECT_DIR/public && chmod +x $CI_PROJECT_DIR/sign-packages.sh && $CI_PROJECT_DIR/sign-packages.sh
        - cd $CI_PROJECT_DIR/public && repo-add --remove --sign wiiu-fling.db.tar.gz `find . -name '*.pkg*' -a ! -name '*.sig'`
    artifacts:
        paths:
            - 'public'
    only:
        - master
#    cache:
#        paths:
#            - packages/*/*.pkg*

arch_container:
    stage: container
    image: docker:stable
    before_script:
        - echo nothing to do...
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest .
        - docker push registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest
    only:
        changes:
            - Dockerfile
