image: registry.example.com/QuarkTheAwesome/wiiu-fling/ci:latest

variables:
    TRY_CACHE: "no"

include:
    - '/packages/wut/ci.yml'
    - '/packages/pkgconf/ci.yml'
    - '/packages/libiosuhax/ci.yml'

stages:
    - container # Docker bits
    - toolchain # Essential toolchain bits - wut etc.
    - libraries # Libraries or groups of libraries that stand alone
    - libraries2 # Libraries that depend on things from "libraries"
    - deploy

pages:
    stage: deploy
    before_script:
        - cd $CI_PROJECT_DIR
        - gpg --batch --import fling-key.pub
        - echo "$FLING_SIGN_KEY" | gpg --batch --import
    script:
        - mkdir -p $CI_PROJECT_DIR/public && cp $CI_PROJECT_DIR/packages/*/*.pkg* $CI_PROJECT_DIR/public/
        - cp fling-key.pub $CI_PROJECT_DIR/public/
        - cd $CI_PROJECT_DIR/public && chmod +x $CI_PROJECT_DIR/sign-packages.sh && $CI_PROJECT_DIR/sign-packages.sh
        - cd $CI_PROJECT_DIR/public && repo-add --sign wiiu-fling.db.tar.gz `find . -name '*.pkg*' -a ! -name '*.sig'`
    artifacts:
        paths:
            - 'public'
    only:
        - master
#    cache:
#        paths:
#            - packages/*/*.pkg*

arch_container:
    stage: container
    image: docker:stable
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/QuarkTheAwesome/wiiu-fling/ci:latest .
        - docker push registry.gitlab.com/QuarkTheAwesome/wiiu-fling/ci:latest
    only:
        changes:
            - Dockerfile
