image: registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest

variables:
    TRY_CACHE: "no"

include:
    - '/packages/wut-linux/ci.yml'
    - '/packages/wut-linux-bin/ci.yml'
    - '/packages/wut-osx/ci.yml'
    - '/packages/wut-msys2/ci.yml'
    - '/packages/pkg-config/ci.yml'
    - '/packages/libiosuhax/ci.yml'
    - '/packages/libdynamiclibs/ci.yml'
    - '/packages/libutils/ci.yml'
    - '/packages/curl-headers/ci.yml'
    - '/packages/sdl2/ci.yml'
    - '/packages/sdl2_gfx/ci.yml'
    - '/packages/sdl2_image/ci.yml'
    - '/packages/sdl2_ttf/ci.yml'
    - '/packages/sdl2_mixer/ci.yml'
    - '/packages/libromfs/ci.yml'

stages:
    - container # Docker bits
    - toolchain # Essential toolchain bits - wut etc.
    - libraries # Libraries or groups of libraries that stand alone
    - libraries2 # Libraries that depend on things from "libraries"
    - sign
    - deploy

before_script:
    - pacman -Sy
      
sign-pkgs:
    stage: sign
    before_script:
        - pacman -Sy
        - cd $CI_PROJECT_DIR
        - gpg --batch --import fling-key.pub
        - echo "$FLING_SIGN_KEY" | gpg --batch --import
    script:
        - chmod +x *.sh && ./deploy-prod.sh
    artifacts:
        paths:
            - 'public'
    only:
        - master

sign-pkgs-staging:
    stage: sign
    script:
        - chmod +x *.sh && ./deploy-staging.sh
    artifacts:
        paths:
            - 'public'
    except:
        - master

arch_container:
    stage: container
    image: docker:stable
    before_script:
        - echo nothing to do...
    services:
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest .
        - docker push registry.gitlab.com/quarktheawesome/wiiu-fling/ci:latest
    only:
        changes:
            - Dockerfile

pages:
    stage: deploy
    script:
        - echo ok
    artifacts:
        paths:
            - 'public'
    environment:
        name: 'Prod'
        url: "https://fling.heyquark.com"
    only:
        - master

deploy-staging:
    stage: deploy
    script:
        - echo ok
    artifacts:
        paths:
            - 'public'
    environment:
        name: 'Staging'
        url: "$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/public/"
    except:
        - master
