# Not using base/devel because it has linux-firmware for some reason
image: base/archlinux:latest

variables:
    TRY_CACHE: "no"

include:
    - '/packages/wut/ci.yml'

stages:
    - toolchain
    - libraries
    - libraries2
    - deploy

before_script:
    - cd dkp && chmod +x install-dkp.sh && ./install-dkp.sh
    - pacman -S --needed --noconfirm base-devel

pages:
    stage: deploy
    # Override the usual script to avoid wasting time installing dkp
    before_script:
        - cd $CI_PROJECT_DIR
        - gpg --batch --import fling-key.pub
        - echo "$FLING_SIGN_KEY" | gpg --batch --import
    script:
        - mkdir -p $CI_PROJECT_DIR/public && cp $CI_PROJECT_DIR/packages/*/*.pkg* $CI_PROJECT_DIR/public/
        - cp fling-key.pub $CI_PROJECT_DIR/public/
        - cd $CI_PROJECT_DIR/public && gpg --batch --detach-sign *.pkg*
        - cd $CI_PROJECT_DIR/public && repo-add --sign wiiu-stuff.db.tar.gz `find . -name '*.pkg*' -a ! -name '*.sig'`
    artifacts:
        paths:
            - 'public'
    only:
        - master
#    cache:
#        paths:
#            - packages/*/*.pkg*
